name: Run Backend and Frontend Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:  
  cypress-tests:
    name: Cypress Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install
          npx install cypress


      - name: Run Server and Cypress Tests (Unix)
        if: runner.os != 'Windows'
        run: |
          cd frontend
          # Start the server in the background
          npm run start:dev &
          cd ..
          # Run Cypress tests
          npx cypress run
        shell: bash

      - name: Run Server and Cypress Tests (Windows)
        if: runner.os == 'Windows'
        run: |
          cd frontend
          # Start the server in the background
          start /B npm run start:dev
          cd ..
          # Run Cypress tests
          npx cypress run
        shell: cmd
